// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/dongwlin/upright-backend/internal/config"
	"github.com/dongwlin/upright-backend/internal/ent"
	"github.com/dongwlin/upright-backend/internal/handler"
	"github.com/dongwlin/upright-backend/internal/server"
	"github.com/dongwlin/upright-backend/internal/service"
	"github.com/google/wire"
	"go.uber.org/zap"
)

// Injectors from wire.go:

func NewHttpServer(conf *config.Config, logger *zap.Logger, db *ent.Client) *server.HttpServer {
	pingHandler := handler.NewPingHandler()
	user := service.NewUser(logger, db)
	auth := service.NewAuth(logger, conf, user)
	authHandler := handler.NewAuthHandler(logger, auth)
	userHandler := handler.NewUserHandler(logger, user)
	httpServer := server.NewHttpServer(conf, logger, pingHandler, authHandler, userHandler)
	return httpServer
}

// wire.go:

var serviceSet = wire.NewSet(service.NewAuth, service.NewUser)

var handlerSet = wire.NewSet(handler.NewPingHandler, handler.NewAuthHandler, handler.NewUserHandler)
