// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/dongwlin/upright-backend/internal/ent/schema"
	"github.com/dongwlin/upright-backend/internal/ent/train"
	"github.com/dongwlin/upright-backend/internal/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	trainFields := schema.Train{}.Fields()
	_ = trainFields
	// trainDescCreatedAt is the schema descriptor for created_at field.
	trainDescCreatedAt := trainFields[7].Descriptor()
	// train.DefaultCreatedAt holds the default value on creation for the created_at field.
	train.DefaultCreatedAt = trainDescCreatedAt.Default.(time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescGender is the schema descriptor for gender field.
	userDescGender := userFields[2].Descriptor()
	// user.DefaultGender holds the default value on creation for the gender field.
	user.DefaultGender = userDescGender.Default.(int8)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[6].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(time.Time)
}
