name: build

on:
  push:
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Build docker image
        run: |
          docker buildx build - upright-backend:dev -o - . > upright-backend.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: upright-backend
          path: upright-backend.tar