env: dev

http:
  host: "0.0.0.0"
  port: 8080

database:
  host: "db"
  port: 5432
  user: "postgres"
  password: "password"
  dbname: "upright"

security:
  paseto:
    key: "symmetric-secret-key (size = 32)"

  we_app:
    app_id: "app-id"
    app_secret: "app-secret"
    grant_type: "grant-type"

log:
  level: "info"
  filename: "./logs/log.jsonl"
  max_size: 5
  max_backups: 10
  max_age: 30
  compress: true
